enyo.Spotlight.js

This fix needs core change https://github.com/enyojs/enyo/pull/1018 before testing.
On app change state between BG and FG, spotlight is not getting any notice.
While focus is on app, it is not blurred because it is not getting any event when app  goes to BG.
- Add blur on windowEvents array to handle on dispatcher feature. (Core) https://github.com/enyojs/enyo/pull/1018
- Blur focus when onblur event comes to Spotlight.
DCO-1.1-Signed-Off-By: Kunmyon Choi kunmyon.choi@lge.com

ENYO-924: Dual focus when system popup (Overlay style app) shown

---

enyo.Spotlight.Util.js

When (0, 0) is tapped on drawers, drawers do not open/close.
We have a code to filter out simulated click event in Spotlight onClick handler.
And, it is checking clientX/clientY == 0 to know is that a simulated event.
That is eventually filter out normal click event also.
Add a flag to indicate the event is generated from click event.
This can be used in Spotlight to exactly distinguish simulated event.
DCO-1.1-Signed-Off-By: Kunmyon Choi kunmyon.choi@lge.com

ENYO-1098: Use simulated flag to distinguish generated tap event

---

enyo.Spotlight.js

##Issue
This issue is found on SmartShare app and we have DEV tracker issue.
When app switching occurs, last focused item is still focused.
more specific, if launching quick setting in smartshare app, then focused item is still focused even after quick setting launched and came back to smartshare.
Step to reproduce
1. Open smartshare app,
2. focus on first item in pointer mode.
3. launch quick setting by pressing settings button
4. See the last focused item.
Problem
The last focused item is still focused.
##FIx
smartshare app is get Cursor Hide event (KeyDown) just after getting the focus event.
The onKeyDown handler is set pointer mode as false only when it is true then spot on last focus.
Following settings button doesn't goes into this logic because it is already in 5way mode.
So, this …

ENYO-1439 last focused item is focused during app swiching.

---

enyo.Spotlight.Container.js
enyo.Spotlight.NearestNeighbor.js

Historically, a Spotlight container has always restored focus to
its last-spotted child when focus was returned to the container via
a 5-way event.
In some cases, though, it would be preferable to let Spotlight's
nearest-neighbor algorithm find and focus the container child
closest to the 5-way event's originating control. This would be
useful in cases (like a scroller) where we want to keep focus
inside the container by default, but where it's not important (and
may be confusing) to restore focus state when the container is
re-entered.
In this change, we implement a simple version of this feature. If
a container has the property `spotlightRememberFocus: false`, then
we let the nearest-neighbor algorithm find the child to spot when
the container gets 5-way focus.
This simple …

ENYO-1444: Add `spotlightRememberFocus` feature for containers

---

lib/VDRSpotlightSupport.js

For expediency during initial development, enyo/VirtualDataRepeater
had direct awareness of (and therefore a dependency on) Spotlight.
We now factor this out so that enyo/VirtualDataRepeater knows
nothing of Spotlight, and Spotlight itself provides a mixin
allowing Spotlight awareness to be added to VDR as needed by
library or app code.
ENYO-DCO-1.1-Signed-Off-By: Gray Norton (gray.norton@lge.com)

ENYO-1617: Factor Spotlight support out of enyo/VirtualDataRepeater

---

lib/spotlight.js

Supporting accessibilityDisabled for spotlight focus.
If accessibilityDisabled is true, set tabindex as null considering
dynamic change.
https://jira2.lgsvl.com/browse/ENYO-1689
Enyo-DCO-1.1-Signed-off-by: Jaewon Jang <jaewon98.jang@lgepartner.com>

ENYO-1689: Accessibility: migration accessibilityDisabled to enyo 2.6

---

lib/spotlight.js

Accroding to accessibility UX guide, accessibility is only supported on
5 way mode, so we don't set focus on pointer mode.
https://jira2.lgsvl.com/browse/ENYO-2032
Enyo-DCO-1.1-Signed-off-by: Jaewon Jang <jaewon98.jang@lgepartner.com>

ENYO-2032: Accessibility: popup position is wrong.

---

lib/spotlight.js

Issue:
- Focus moves to first visible item when trying to move out from
datalist.
Fix:
- Give different focusType to _5WayMove case.
Signed-off-by: Kunmyon Choi <kunmyon.choi@lge.com>

ENYO-2158: Focus jumps to first visible child when focus move out from datalist

---

lib/spotlight.js

We (fairly) recently added a `next` property to the
`onSpotlightBlur` event, indicating which element will be focused
next.
We now add a similar `previous` property to `onSpotlightFocus` and
`onSpotlightFocused`.
These properties are intended to let handlers discriminate on the
basis of where focus is coming from / going when implementing
special-case logic.
The `previous` property specifically was useful in refining 5-way
scrolling behavior in Moonstone, to switch between item-at-a-time
and page-at-a-time scrolling depending on where the focus
previously was (see moonstone/Scrollable).
Enyo-DCO-1.1-Signed-Off-By: Gray Norton (gray.norton@lge.com)

Add `previous` property to `onSpotlightFocus`, `onSpotlightFocused`

---

lib/spotlight.js

- When there is no focus-able item on screen, and user want to get keyup
event by Signals. Spotlight blocks onKeyUp event and Signals can not
get the event..
- Originally it is blocked to block tap event hadling when pressing
enter on pointer mode.
- Return false on _bSupressSelectionOnNextKeyUp case of onKeyUp.
- This will allow to get onkeyup event from Signals but will not process
tap when press enter on pointer mode.
Signed-off-by: Kunmyon Choi <kunmyon.choi@lge.com>

ENYO-2236: Spotlight drop keyup event when there is no focus-able item on screen

---

lib/spotlight.js

Because we were effectively async'ing the observing and unobserving of disappearance whenever the currently spotted control changed, if there were a sequence of multiple spots, we could potentially be using an incorrect reference to the controls we were to observe/unobserve, as we would be grabbing the last reference to the controls.
We made sure that we utilize the correct reference to the controls by using the local var instead of the global var for the current control. Additionally, we made sure to tweak the `_setDefaultDisappearControl` method such that it attempts to retrieve the default disappear control from the control we are observing, as opposed to the global, current Spotlight control.
Enyo-DCO-1.1-Signed-off-by: Aaron Tam <aaron.tam@lge.com>

ENYO-2265: Observe and unobserve disappearance for the correct controls.

---

src/container.js
src/spotlight.js

Instead of changing the tabindex onSpotlightFocused, set any spottable
control with a tabindex of -1 (programmatically focusable) on create.
This required moving the hacky Component.create code from container
to spotlight so we only hacked it once for this lib.

Fixes ENYO-2430

---

src/spotlight.js

If spotlight alternates between a spottable non-label and a label or
control with accessibility disabled, focus isn't changed when returning
to the non-label because it wasn't set to the label when it was
spotted. So, if the spotted control can't receive focus and there is a
document.activeElement, blur it so it can receive focus again.

Fixes ENYO-2431

---

src/spotlight.js

Issue:
When floating app is getting pointer, foreground app doesn't know about
mouse leave. So, the foregrund app doesn't un-highlight focus when mouse
move to floating app. This resulting in dual focus issue.
Fix:
Add webOS specific event, webOSMouse, to let app know mouse leave and
enter. This event is fired when QT::Leave and QT::Enter event comes.
We directly dispatch this event in enyo-webos index.js.
And, force unspot when webOSMouse leave event comes.
Enyo-DCO-1.1-Signed-off-by: Kunmyon Choi <kunmyon.choi@lge.com>

ENYO-1742: unspot on webOSMouse leave

---

src/spotlight.js

Blurring the activeElement could inadvertently blur an unspottable
control (like the moonstone/Input within a moonstone/InputDecorator).
Instead, only blur the previously spotted control which would have been
focused by spotlight before.

Fixes ENYO-2519

---

src/neighbor.js
src/spotlight.js

Spotlight has a feature allowing a "default" target to be set for
a 5-way move in a specific direction from a specific origin. When
a default target is set, it short-circuits the nearest neighbor
calculation that would normally happen.
From an implementation point of view, the logic for identifying and
returning the default target has historically resided inside the
`getNearestNeighbor()` method, but with the recent addition of the
`spotlightRememberFocus` option for containers, this coupling can
now cause an infinite-recursion issue in certain cases.
To avoid such cases, we will factor the default-target-acquisition
logic out of `getNearestNeighbor()` so that it can be applied in
the cases where it is needed and skipped in the cases where it is
problematic. This factoring seems …

ENYO-2524: Factor "default direction" logic out of nearest neighbor

---

src/muter.js
src/spotlight.js

Issue:
- When floating app is request window focus, background app doesn't get
mouse events.
- But, when background app is actively move focus to other, dual focus
can be happens.
- This can be happens by plug out drive while playing music on player.
Fix:
- We mute spotlight on window blur. So, any kind of focus move on
background app can be done safely without highlighting focus.
- Unmute when window get focus back. So, last focused item can be highlighted.
Enyo-DCO-1.1-Signed-off-by: Kunmyon Choi <kunmyon.choi@lge.com>

ENYO-2548: Do mute on window blur and webOSMouse leave

---

src/spotlight.js

Issue:
Music player has close button and hide it on blue. When user move mouse
pointer from close button to outside of player, sing icon is getting
focus back even on pointer mode. This is because webOSMouse event comes
on mouse leave, and spotlight handler is set pointer mode false before
calling unspot. Close button is hide itself while it is focused by blur
handler.
Fix:
We don't need to change pointer mode as false before calling unspot to
solve previous dual focus issue. So, we set pointer mode true prior to
unspot. It will block spot call on disappear routine.
Enyo-1.1-DCO-Signed-off-by: Kunmyon Choi <kunmyon.choi@lge.com>

ENYO-2629: Set pointer mode true before unspot on webOSMouse leave

---

src/muter.js
src/spotlight.js

Issue:
- When floating app is request window focus, background app doesn't get
mouse events.
- But, when background app is actively move focus to other, dual focus
can be happens.
- This can be happens by plug out drive while playing music on
player.
Fix:
- We mute spotlight on window blur. So, any kind of focus move on
background app can be done safely without highlighting focus.
- Unmute when window get focus back. So, last focused item can
be highlighted.
- We also add platform specific event keyboardStateChange to handling
mouse hover on VKB then hide VKB case. And unmute on VKB hide.
Enyo-1.1-DCO-Signed-off-by: Kunmyon Choi <kunmyon.choi@lge.com>

ENYO-2548: Dual focus on both overlay/card app

---

src/spotlight.js

If the spotted control were disabled, destroyed hidden, etc after it
were spotted but in the same frame, the disappear observers would not
have been set yet (they're async for perf reasons) so an otherwise
unspottable control would be spotted.
Added checks before observing to ensure the spotted control is still
valid.

Fixes ENYO-1706

---

src/spotlight.js

The setTimeout callback was using variables whose values could be no
longer valid when the callback was executed. oExCurrent would always
point to the previous at the time the callback was called but may not
be the previous at the time the timeout was scheduled. Similarly,
oControl may not need to be observed if it was no longer the currently
spotted control when the callback is called.
Instead, ensure that the timeout is only scheduled if there isn't one
pending, bind oExCurrent to the callback so the previously spotted
control is correctly unobserved, and use _oCurrent in the callback so
the currently spotted control is observed.

Fixes ENYO-2756

---

src/container.js

We have long had, for special cases, a public API allowing the
last focused child of a Spotlight container to be explicitly set.
We have a new use case where we want to set it to `null`, so
extending the API accordingly.
Enyo-DCO-1.1-Signed-Off-By: Gray Norton (gray.norton@lge.com)

ENYO-2744: Allow setting lastFocusedChild to null

---

src/spotlight.js

Issue
When a control is destroyed, Spotlight is unable to get its parent
because it has already been nulled by the time the destroyed observers
are invoked.
Fix
add back the call to retrieve the first spottable control as a fallback

Fixes ENYO-2770

---

src/spotlight.js

Enyo-DCO-1.1-Signed-Off-By: Gray Norton (gray.norton@lge.com)

ENYO-2860: Only call native focus() if the control is still spotted

---

src/neighbor.js

We have long had logic in Spotlight to use a container's last
focused child when performing a nearest-neighbor calculation from
the container. However, that logic didn't account for the case
where there were nested containers. We adjust it so that it now
does.
Enyo-DCO-1.1-Signed-Off-By: Gray Norton (gray.norton@lge.com)

ENYO-2657: Always calculate neighbor from last non-container

---

src/spotlight.js

When the current application is blurred and a `hold`/`holdpulse` is currently active, this event continues in the newly active application.
We always end any holds when blurring the application, similar to our calls to `unspot` and `setPointerMode(false)`.
Enyo-DCO-1.1-Signed-off-by: Aaron Tam <aaron.tam@lge.com>

ENYO-2880: End any holds when blurring.

---

src/spotlight.js

When there are standard HTML elements nested in Enyo controls, spotting with the pointer does not work correctly as the first spottable parent would not be found.
Inspired by the fix from https://github.com/enyojs/spotlight/pull/205, we have consolidated this logic into `_getSpottableTarget` (the artist formerly known as `_getTarget`) as the operations were very related, and semantically we are trying to find a _spottable_ target, and not a target based on an id.
Enyo-DCO-1.1-Signed-off-by: Aaron Tam <aaron.tam@lge.com>

ENYO-1608: Thoroughly discovers the spottable target for a given node.

---

src/spotlight.js

Fix for ENYO-2784 and ENYO-2485
https://jira2.lgsvl.com/browse/ENYO-2784?filter=-1
Enyo-DCO-1.1-Signed-off-by: Jaewon Jang jaewon98.jang@lgepartner.com

ENYO-2784: When the LightPanels are switched, screen reader doesn't read the focused item.

---

src/spotlight.js

We mute('window.focus') spotlight on webOSLeave event to prevent unwanted focus highlight on active app change like plug out USB media while showing other floating type app. A floating type window of webOs is not get key event while hover and it is actually not active app before the app is specifically request key focus.  Therefore, active app (at the back) is getting the key event while hover over floating app. But, no webOSEnter event comes to active app. As a result, ghost focus problem happens when user press 5way key while hover pointer over floating app. User can see tooltip but there is no focus highlighted on active app because it is still muted.
We unmute('window.focus') on 5 way key event and pointer hide event comes. so, it can safely release mute state when user want to change …

ENYO-2912: Unmute('window.focus') on key down and pointer hide

---

src/container.js

Issue:
We have spotlightRememberFocus option on spotlight container, but this only work on 5way key press case. So, if we want to apply this option on popup then it is not work in expected way. Meaning, remember last focus on show.
Fix:
Add a condition on getLastFocusedChild to pick first control when spotlightRememberFocus is false.
Enyo-DCO-1.1-Signed-off-by: Kunmyon Choi kunmyon.choi@lge.com

ENYO-3091: Support spotlightRememberFocus option on getLastFocusedChild

---

src/neighbor.js

Issue:
In case of app close button, panel doesn't contains close button
but other control should consider it when calculating nearest
neighbor on the same level of div.
Fix:
Add an option to getNearestNeighbor that can explicitly add extra
candidates to current siblings.

ENYO-3228: Add extraCandidates option to getNearestNeighbor

---

src/spotlight.js

Issue:
If switch app while drag, down event is not cleaned up. This make
app in dragging status after switch back to previously focused app.
Fix:
Explicitly call gesture.up when gesture.downEvent is not null on
window.blur event comes.

ENYO-3093: Clean up gesture downEvent on window.blur

---

src/spotlight.js

Issue
:focusType info is not delagate until onSpotlightFocused handler
Fix
:delegate focusType info from onSpotlightFocus to onSpotlightFocused

ENYO-3319 : Delegate focusType property to onSpotFocused

---

src/container.js

scene closed by 4way right and back key
Issue:
Spotlight container focused handler find nearest neighbor when
spotlightRememberFocus false. It use last5WayEvent to find
nearest neighbor control. The last5WayEvent is reset to null when
onSpotlightSelect event comes. When scene change is triggered by
non 5way event (back key), last5WayEvent is remains after scene
change. This makes container find nearest neighbor which is invalid.
Fix:
When we find nearest neighbor, it assume the last 5way control is
visible and control bounds is valid. In problem case, the last 5way
control is not visible and control bounds is not valid. So, we can
filter out the invalid case by checking absolute showing status.

ENYO-3368: Focus jump to first item on spotlight container if previous

---

src/spotlight.js

Issue
:Button's audio guidance is not fire when window restore focus
Fix
:Apply dom node blur in unspot func
Enyo-DCO-1.1-Signed-off-by: Changgi Lee <changgi.lee@lge.com>

ENYO-3381 : Button is not read when window restore focus

---

src/spotlight.js

Issue:
When open and close popup by 5way key press, we expect that we are in 5way mode.
Unexpected mouse move event with same position fired on every show/hide if we do 
dom.focus on animating element. And the pointer mode is still false in this case.
We have a logic that is dropping mouse move event which doesn't
actually changed position or count of event is less then 2. Logically, it should be filtered 
out in here. But, problem happens when pointer mode is false because it is only update
last position on pointer mode.
Fix:
We noticed that the center mouse move event on cursor hide is now doesn't come.
So, we removing spotlight pointer mode check from clientXYChanged. And, now It
can always cache last mouse position to compare movement.
Enyo-DCO-1.1-Signed-off-by: Kunmyon Choi …

ENYO-3421: Spotlight focus jump or lost when show/hide popup repeatedly

---

src/container.js
src/neighbor.js

spotlightRememberFocus is false
The getNearestNeighbor is compares position between container itself and
outside control. But, when focus is moving out from container it is
expecting compare position with its last focused child not container
itself. When container have spotlightRememberFocus false, we reset last
focus to null. This behavior affect getNearestNeighbor logic and
getLastFocusedChild return first child.
Revert previous change that is supporting spotlightRememberFocus false
on explicit spot. But, we support same feature on popup and notification
by adding explicit event that is reset last focused child on container
and calling it on hide.

ENYO-3425: Nearest neighbor compare position with first child when

---

src/spotlight.js

spotlightPreserveAcceleration property as true.
When spotlight container control have only one spottable item,
just like ExpandableListItem family, it cancel 5way key acceleration.
We add a property which can be given on container control that
is skipping acceleration cancel logic.

ENYO-3430: Preserve acceleration when container control have

---

src/spotlight.js

Issue:
We dont dispatch onSpotlightBlur on onDisappear routine. That is because
we doesn't have any usecases for this case. But, store demo app recently
reported an issue regarding to this because they need to recover some
state on blur event.
Fix:
We dispatch onSpotlightBlur on disappear, so that any control that is
unhighlight focus can get event.

ENYO-3451: Dispatch onSpotlightBlur on disappear

---

src/spotlight.js

Issue:
We skip highlight but dispatch onSpotlightFocus on setCurrent while
muted. But, we skip dispatch onSpotlightBlur on unspot when there is no
highlight focus on screen by checking _bFocusOnScreen variable. This
leads missmatch between event.
Fix:
We skip only unhighlight from unspot when _bFocusOnScreen is false. And
do dispatch onSpotlightBlur event.

ENYO-3450: Only skip unhighlight on unspot and dispatch blur event.
