- enyo.Spotlight.js
Cherry-picking the changes from https://github.com/enyojs/spotlight/pull/164 into `master`, creating a PR for tracking purposes.
> ENYO-924 (master)

- enyo.Spotlight.Util.js
Cherry-picking the changes from https://github.com/enyojs/spotlight/pull/167 into `master`, creating a PR for tracking purposes.
> ENYO-1098 (master)

- enyo.Spotlight.js
This work is related to @graynorton's new-list-wip-graynorton branches from https://github.com/enyojs/enyo/pull/1104 and https://github.com/enyojs/moonstone/pull/2057.
> 2.6.0-pre.4 changes

- enyo.Spotlight.js
Cherry-picking the changes from https://github.com/enyojs/spotlight/pull/171 into `2.6.0-pre.4-dev`, creating a PR for tracking purposes.
> ENYO-1439 last focused item is focused during app swiching.

- lib/container.js
- lib/neighbor.js
- lib/spotlight.js
Migrated to modularized codebase for merging into 2.6.0-dev.
Includes a new feature, `spotlightRememberFocus`, and a one-line bug fix.
> Compilation of changes since 2.6.0-pre.4

- lib/accelerator.js
- lib/container.js
- lib/muter.js
- lib/neighbor.js
- lib/scrolling.js
- lib/spotlight.js
- lib/states.js
- lib/testmode.js
- lib/util.js
Enyo-DCO-1.1-Signed-off-by: Roy Sutton <roy.sutton@lge.com>
> ENYO-1526 Convert inline docs to modules

- src/spotlight.js
> prevent setting focus when originator is a label

- src/muter.js
- src/spotlight.js
This reverts commit 85b7e79ed6250249340fcf1ca696d8b28f5287fd, reversing
changes made to a64da33987df4677583573ed05c63dbcf3edb693.
> Revert "Merge pull request #217 from enyojs/ENYO-2548-kunmyonchoi"

- src/spotlight.js
Reverting https://github.com/enyojs/spotlight/commit/cd1f9e5da73f66c1874c5d8d23981085bd416973 and https://github.com/enyojs/spotlight/commit/c8f2dcc03bf7f87f34b84d0e0cb59b6280c5a92d.
> ENYO-2796: Revert ENYO-2722, ENYO-2770

- src/spotlight.js
This reverts commit cd1f9e5da73f66c1874c5d8d23981085bd416973, reversing
changes made to 067b6e54e2e93fca070c3e92fb6571dc01d715ec.
> Revert "Merge pull request #222 from enyojs/ENYO-2722-stephen" (2.6.0-pre.19.2)

- src/container.js
- src/spotlight.js
Restores the fixes for ENYO-2722 and ENYO-2770 and correctly addresses
the regression caused by these in ENYO-2796.
> Fixes ENYO-2722, ENYO-2770, ENYO-2796

- src/VDRSpotlightSupport.js
Enyo-DCO-1.1-Signed-off-by: Roy Sutton <roy.sutton@lge.com>
> ENYO-2964 Fix mixin declarations

- src/spotlight.js
Changes from https://github.com/enyojs/spotlight/pull/238.
> PLAT-15245 (2.6.2-rc.1)

- src/spotlight.js
Enyo-DCO-1.1-Signed-off-by: Jason Robitaille <jason.robitaille@lge.com>
> ENYO-3026: Improved Touch Support for Spotlight

- src/spotlight.js
Enyo-DCO-1.1-Signed-off-by: Roy Sutton <roy.sutton@lge.com>
> ENYO-3018 Fixup doc deficiencies

- src/spotlight.js
Changes from https://github.com/enyojs/spotlight/pull/240.
> ENYO-1608: Thoroughly discovers the spottable target for a given node. (2.6.2-rc.2)

- package.json
Enyo-DCO-1.1-Signed-off-by: Aaron Tam <aaron.tam@lge.com>
> ENYO-3047: Update (allthedependencies).

- src/spotlight.js
Changes from https://github.com/enyojs/spotlight/pull/230.
> ENYO-2485 (2.6.3-rc.1)

- src/spotlight.js
Changes from https://github.com/enyojs/spotlight/pull/245.
> ENYO-2912 (2.6.3-rc.1)

- src/spotlight.js
Changes from https://github.com/enyojs/spotlight/pull/236.
> ENYO-2784 (2.6.3-rc.1)

- README.md
Enyo-DCO-1.1-Signed-off-by: Derek Tor derek.tor@lge.com
> Updated readme links for 2.6 docs

- src/container.js
Changes from https://github.com/enyojs/spotlight/pull/246.
> ENYO-3091 (2.6.4-rc.1)

- README.md
Enyo-DCO-1.1-Signed-off-by: Derek Tor derek.tor@lge.com
> ENYO-2893: updated readme to match docs

- src/container.js
Enyo-DCO-1.1-Signed-off-by: Jeremy Thomas <jeremy.thomas@lge.com>
> ENYO-3019: IE8 Support Removal

- src/neighbor.js
Merge ENYO-3228 to release-2.6.3
Enyo-DCO-1.1-Signed-off-by: Roy Sutton roy.sutton@lge.com
> Enyo 3228 263

- src/spotlight.js
Changes from https://github.com/enyojs/spotlight/pull/254 and https://github.com/enyojs/spotlight/pull/234.
> ENYO-3093 (2.6.3-rc.2)
